import { useMemo } from 'react';
import { Paragraph, Section } from '../apis/components/Common';
import { MimicUtils } from '../utils/MimicUtils';

export default function Example() {
  const script = useMemo(() => MimicUtils.getDemoScript(), []);

  return (
    <Section title="Example: Automate saucedemo.com">
      <Paragraph>
        The snippet below is a complete example generated by Mimic, automating a purchase flow on saucedemo.com.
      </Paragraph>
      <Paragraph>
        You can paste and run it in the extension sidebar script editor. The runtime provides globals like page, browser, ai, expect, and wait.
      </Paragraph>
      <pre style={{ background: '#0f172a', color: '#e2e8f0', padding: 16, borderRadius: 8, overflowX: 'auto' }}>
        <code>{script}</code>
      </pre>
    </Section>
  );
}
