import { useMemo } from 'react';
import { CodeBlock, Paragraph, Section } from '../../shared/components/Common';
import { MimicUtils } from '../demo/utils/MimicUtils';

export default function Example() {
  const script = useMemo(() => MimicUtils.getDemoScript(), []);

  return (
    <Section title="Example: Automate saucedemo.com">
      <Paragraph>
        The snippet below is a complete example generated by Mimic, automating a purchase flow on saucedemo.com.
      </Paragraph>
      <Paragraph>
        You can paste and run it in the extension sidebar script editor. The runtime provides globals like page, browser, ai, expect, and wait.
      </Paragraph>
      <CodeBlock code={script} />
    </Section>
  );
}
